<?php

namespace AppBundle\Repository;
use AppBundle\Entity\OAuthToken;

/**
 * OAuthTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OAuthTokenRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return OAuthToken | null | object
     */
    public function getLastToken() {
        return $this->findOneBy([], [
           'createdAt' => 'DESC'
        ]);
    }
}
