<?php
namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function findByOnline()
    {
        $builder = $this->createQueryBuilder('v');

        $query = $builder->andWhere(
            $builder->expr()->isNotNull('v.publishedAt')
        )
        ->getQuery();

        return $query->getResult();
    }

    /**
     * @param $search
     * @return array
     */
    public function search($search)
    {
        $builder = $this->createQueryBuilder('v');

        if (!is_null($search)) {
            $builder->where(
                $builder->expr()->orX(
                    $builder->expr()->like(
                        'v.title',
                        $builder->expr()->literal('%'.$search.'%')
                    ),
                    $builder->expr()->like(
                        'v.description',
                        $builder->expr()->literal('%'.$search.'%')
                    ),
                    $builder->expr()->like(
                        'v.captions',
                        $builder->expr()->literal('%'.$search.'%')
                    )
                )
            );
        }
        $query = $builder->andWhere($builder->expr()->isNotNull('v.publishedAt'))
            ->orderBy('v.publishedAt', 'DESC')
            ->getQuery();

        return $query->getResult();
    }
}
