<?php
namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends EntityRepository
{
    /**
     * @param User $user
     * @return array
     */
    public function listByUser(User $user)
    {
        return $this->findBy(array(
            'user' => $user
        ));
    }
}
