<?php
namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function findByOnline()
    {
        $builder = $this->createQueryBuilder('v');

        $query = $builder->andWhere(
            $builder->expr()->isNotNull('v.publishedAt')
        )
        ->getQuery();

        return $query->getResult();
    }
}
